name: Android CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Run docker build
        run: |
          docker build . -t app-build-image
          docker run --name app-build app-build-image
          docker cp app-build:/apks .
      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: apks
